### ISSUE TITLE
No readable documentation

### ISSUE THREAD

**Issue by arcas0803** [dart-lang/angular2_components_example#4]
No way to see what components are available, their attributes...
Not to much elements at all.
Is there any information about the acx gallery promoted on the dart summit?

**Comment by daniel-v** [comment]
Hi there!

For now it's a work in progress. They did say that they are working on releasing more components. 
Documentation and the gallery will eventually come. For now the best place for documentation are the samples' code:
https://github.com/dart-lang/angular2_components_example/blob/master/lib/app_component.html

Also, there is a list of components you can use right now here:
https://github.com/dart-lang/angular2_components

I'll give this a thumbs up anyway, I am very excited about this too.

**Comment by kwalrath** [comment]
Some more links:

* [API reference: angular2_components](https://www.dartdocs.org/documentation/angular2_components/latest)
* [Code Lab: AngularDart Components](https://webdev.dartlang.org/codelabs/angular2_components)
* [More resources](https://webdev.dartlang.org/codelabs/angular2_components/what-next)
